### ISSUE TITLE
c3d_to_bvh or bvh_to_c3d?

### ISSUE THREAD

**Issue by Xinqi-L** [lasagnaphil/c3d-to-bvh#1]
I'm longing for a way to convert c3d to bvh. But the code seems to be a way for converting bvh to c3d?
Is there a way to convert c3d to bvh?

**Comment by lasagnaphil** [comment]
It is c3d to bvh, but it’s tailor-made to a specific format (lower-body Vicon Plug-in Gait markers) for biomechanics purposes. It’s not intended for general use, this repo was meant to be used inside our research lab few years ago.

If you want to convert c3d motion data to bvh in general, I highly recommend either using MotionBuilder, or write your own optimization-based skeletal fitting code.
